services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tomcat:
    image: urgverif:latest
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./config-urgverif.prop:/usr/local/tomcat/webapps/ROOT/config-urgverif.prop:ro
    depends_on:
      - postgres

volumes:
  postgres-data: