INSERT INTO vehicule(immatriculation, type_engin, id_centre)
VALUES ('vsav', 'VSAV', 1),
('FR941YQ', 'VSAV', 1);

DELETE FROM materiel WHERE id_vehicule = 'vsav';

-- Materiel de base pour VSAV
INSERT INTO materiel(id_compartiment, id_vehicule, nom, quantite)
VALUES (1, 'vsav', 'Bassin de lit', 1),
(1, 'vsav', 'Sacs pour bassin', 2),
(1, 'vsav', 'Draps UU', 6),
(1, 'vsav', 'Housses mortuaires', 2),
(1, 'vsav', 'Kits COVID', 3),
(2, 'vsav', 'Ecran à sélection tactile', 1),
(2, 'vsav', 'Boite à aiguille', 1),
(2, 'vsav', 'Manugel', 1),
(2, 'vsav', 'Boites de gants', 3),
(3, 'vsav', 'Damage Control', 1),
(3, 'vsav', 'Section de membre', 1),
(3, 'vsav', 'Kit aspiration + aspirateur manuel', 1),
(3, 'vsav', 'Kit Brulé', 1),
(3, 'vsav', 'Protections SP', 3),
(3, 'vsav', 'Protection Malade', 1),
(4, 'vsav', 'Sac 1er secours', 1),
(4, 'vsav', 'Chaise de transport', 1),
(4, 'vsav', 'Couvertures bactériostatique', 2),
(4, 'vsav', 'DSA', 1),
(5, 'vsav', 'Electrode adulte branchée', 1),
(5, 'vsav', 'Rasoirs + compresses', 2),
(5, 'vsav', 'Ciseaux GESCO', 1),
(5, 'vsav', 'Electrode adulte', 1),
(5, 'vsav', 'Electrode enfant', 1),
(5, 'vsav', 'Cardio-pompe', 1),
(5, 'vsav', 'Pansement absorbant', 1),
(6, 'vsav', 'Compresses stériles', 10),
(6, 'vsav', 'Bandes nylon 10cm', 4),
(6, 'vsav', 'Bandes nylon 4cm', 4),
(6, 'vsav', 'Filet tubulaire "bras"', 1),
(6, 'vsav', 'Filet tubulaire "main"', 1),
(6, 'vsav', 'Filet tubulaire "doigt"', 1),
(6, 'vsav', 'Sparadraps', 2),
(6, 'vsav', 'Chlorures de sodium 45ml', 2),
(6, 'vsav', 'Bétadines 10ml', 10),
(6, 'vsav', 'Dakins 60ml', 2),
(6, 'vsav', 'Ciseaux GESCO', 1),
(6, 'vsav', 'Thermomètre frontal', 1),
(6, 'vsav', 'Compresses occulaire', 2),
(6, 'vsav', 'Garrot', 1),
(7, 'vsav', 'C.H.U.T', 2),
(7, 'vsav', 'Pansements absorbant 15x20', 4),
(7, 'vsav', 'Poches de froid', 4),
(7, 'vsav', 'Echarpes triangulaires', 4),
(7, 'vsav', 'Couvertures de survie', 4),
(7, 'vsav', 'Kit A.E.S', 1),
(8, 'vsav', 'Masques HC Adulte', 3),
(8, 'vsav', 'Masque MC Adulte', 1),
(8, 'vsav', 'Canules de Guedel T0-1-2-3-4 + Filtre', 1),
(8, 'vsav', 'Sondes Aspiration Adulte', 2),
(8, 'vsav', 'Paire de lunette 02', 1),
(8, 'vsav', 'Masques HC Pédiatrique', 3),
(8, 'vsav', 'Masque MC Pédiatrique', 1),
(8, 'vsav', 'Sonde Aspiration Pédiatrique', 1),
(9, 'vsav', 'Insuflateur Adulte', 1),
(9, 'vsav', 'Insuflateur pédiatrique et nourisson', 1),
(10, 'vsav', 'Kit accouchement', 1),
(11, 'vsav', 'Carburant + AdBlue', 0),
(11, 'vsav', 'Liquide Refroidissement', 0),
(11, 'vsav', 'Lave Glace', 0),
(11, 'vsav', 'Huile moteur', 0),
(12, 'vsav', 'Lot de bord', 1),
(12, 'vsav', 'Bip télépéage', 1),
(12, 'vsav', 'Télécommande portail CIS', 1),
(12, 'vsav', 'Ecran de sélections - gyro....', 1),
(12, 'vsav', 'GPS', 1),
(12, 'vsav', 'Gilets haute visibilité', 3),
(12, 'vsav', 'Plan parcellaire', 1),
(12, 'vsav', 'Boites de gants', 3),
(12, 'vsav', 'Lot SINUS', 1),
(12, 'vsav', 'Polycoise', 1),
(12, 'vsav', 'Coupe ceinture', 1),
(12, 'vsav', 'Classeur note de service SSSM', 1),
(12, 'vsav', 'Radio', 1),
(12, 'vsav', 'Lecteur de carte', 1),
(12, 'vsav', 'Fiches Bilan', 10),
(12, 'vsav', 'Rubalise', 1),
(13, 'vsav', 'Lampes LED', 3),
(13, 'vsav', 'Rouleau de sac DASRI', 1),
(13, 'vsav', 'Paires de gants', 2),
(13, 'vsav', 'Triangle de pré signalisation', 1),
(13, 'vsav', 'Petite pince', 1),
(13, 'vsav', 'LSPCC', 1),
(13, 'vsav', 'Extincteur poudre', 1),
(13, 'vsav', 'L.S.A', 1),
(13, 'vsav', 'Poubelle DASRI', 1),
(13, 'vsav', 'Cales de roue', 2),
(14, 'vsav', 'Démarrage', 0),
(14, 'vsav', 'Boite de vitesse', 0),
(14, 'vsav', 'Voyant tableau de bord', 0),
(14, 'vsav', 'Klaxon', 0),
(14, 'vsav', '2 tons', 0),
(14, 'vsav', 'Clignotants et Feux de détresse', 0),
(14, 'vsav', 'Feux de route', 0),
(14, 'vsav', 'Feux de croissement', 0),
(14, 'vsav', 'Feux antibrouillard avant', 0),
(14, 'vsav', 'Feux antibrouillard arrière', 0),
(14, 'vsav', 'Gyrophare Avant et Arrière', 0),
(14, 'vsav', 'Feux de gabarit', 0),
(14, 'vsav', 'Bande de détresse arrière', 0),
(15, 'vsav', 'Carroserie', 0),
(15, 'vsav', 'Optiques de phrase', 0),
(15, 'vsav', 'Optiques gyrophare', 0),
(15, 'vsav', 'Rétroviseurs', 0),
(15, 'vsav', 'Vitres et parebrise', 0),
(15, 'vsav', 'Pneumatique', 0),
(15, 'vsav', 'Fermeture normale des portes', 0),
(16, 'vsav', 'Pochette sangle plan dur', 1),
(16, 'vsav', 'Sangle de maintien M-Sup', 1),
(16, 'vsav', 'Sangle de maintien M-Inf', 1),
(16, 'vsav', 'Colliers cervicaux Adultes', 2),
(16, 'vsav', 'Colliers cervicaux Pédiatriques', 2),
(17, 'vsav', 'Portoir souples assis', 1),
(17, 'vsav', 'Portoir allongé', 1);

INSERT INTO materiel(id_compartiment, id_vehicule, nom, quantite)
SELECT id_compartiment, 'FR941YQ', nom, quantite
FROM materiel
WHERE id_vehicule = 'vsav';